const SET_SOCKET = 'SET_SOCKET'
const SET_LOADING = 'SET_LOADING'
const SET_API_FEEDBACK = 'SET_API_FEEDBACK'
const SET_ROLE = 'SET_ROLE'
const SET_LAST_UNDREAD_MESSAGE_INDEX = 'SET_LAST_UNDREAD_MESSAGE_INDEX'
const SET_UNREAD_MESSAGES_AMOUNT = 'SET_UNREAD_MESSAGES_AMOUNT'

const actions = {
    SET_SOCKET,
    SET_LOADING,
    SET_API_FEEDBACK,
    SET_ROLE,
    SET_LAST_UNDREAD_MESSAGE_INDEX,
    SET_UNREAD_MESSAGES_AMOUNT
}

export default actions
