export { setLoading } from './setLoading'
export { setRole } from './setRole'
export { setApiFeedback } from './setApiFeedback'
export { handleApiError } from './handleApiError'
export { handleApiValidation } from './handleApiValidation'

export { subscribePushNotifications } from './subscribePushNotifications'
export { logout } from './logout'
export { pushToTheBottom } from './pushToTheBottom'
export { detectMobileDevice } from './detectMobileDevice'
export { getDefaultAvatar } from './getDefaultAvatar'
export { handleDispatcher } from './handleDispatcher'
